### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by SmallPP420** [lopestom/device_ulefone_Note_11P#1]
hey! just checking in i saw that when u compile github workflows usually runs out of space well recently i got access to an ubuntu server and i can compile twrp 11 with these trees for u if u want

**Comment by SmallPP420** [comment]
hey also theres a little issue in the readme :)

update
lunch twrp_NOTE_11P-eng 
to
lunch twrp_Note_11P-eng

**Comment by lopestom** [comment]
> hey also theres a little issue in the readme :)
> 
> update lunch twrp_NOTE_11P-eng to lunch twrp_Note_11P-eng

Tks
That's really not important now.

> hey! just checking in i saw that when u compile github workflows usually runs out of space well recently i got access to an ubuntu server and i can compile twrp 11 with these trees for u if u want

What difference as workflows?

I only need know if DT is good or not to compiling.......... 🔢

**Comment by SmallPP420** [comment]
fair enough i guess but i have also found a little issue in boardconfig

https://github.com/lopestom/device_ulefone_Note_11P/blob/android-11/BoardConfig.mk#L49

**Comment by SmallPP420** [comment]
``What difference as workflows?``

it has more ram and storage and can use ccache

**Comment by SmallPP420** [comment]
also curiosity got the best of me and i compiled it anyways and it seems like the boot image is

empty??

**Comment by lopestom** [comment]
> fair enough i guess but i have also found a little issue in boardconfig
> 
> https://github.com/lopestom/device_ulefone_Note_11P/blob/android-11/BoardConfig.mk#L49

When you apoint issue so please, apoint the solution.
I cannot look any issue in that.

> `What difference as workflows?`
> 
> it has more ram and storage and can use ccache

How we can have acess to it?

**Comment by SmallPP420** [comment]
buildvariant=user in the boardconfig

**Comment by SmallPP420** [comment]
``How we can have acess to it?``

i can somehow privately message u the stuff

**Comment by SmallPP420** [comment]
do you have telegram? i can message you there

**Comment by lopestom** [comment]
> buildvariant=user in the boardconfig

This is not important because after file compiled the lunch choose "eng".

> `How we can have acess to it?`
> 
> i can somehow privately message u the stuff

Yes and No. I have TWRP3.6.0_11 compiled a time ago man. If you want see: https://4pda.to/forum/index.php?act=findpost&pid=111598059&anchor=Spoil-111598059-1
 But I'm trying solve the encrypt/decrypt trustkernel. That's not easy in A10 devices. So in the A11 devices is more difficultly.
 
 The storage in workflows stuff because the binaries blobs have more sizes than the img file can. So the TWRP3.6 has more files and so more size too. Like 2~3 files like much languague (1.36MB); file font (3.6MB)..........
 Therefore the rest of files from device is limited.

**Comment by lopestom** [comment]
> 

Sorry. I haven't TG.....

**Comment by SmallPP420** [comment]
hm fair enough

**Comment by SmallPP420** [comment]
ok ill somehow get through making a 4pda account and message u there
